2025-07-08 19:01:40,612 - INFO - Starting remote test execution...
2025-07-08 19:01:40,613 - INFO - Connecting to user@jtmksrv:656
2025-07-08 19:01:40,678 - INFO - Connected (version 2.0, client OpenSSH_7.6p1)
2025-07-08 19:01:40,810 - INFO - Authentication (password) successful!
2025-07-08 19:01:41,001 - INFO - [chan 0] Opened sftp connection (server version 3)
2025-07-08 19:01:41,002 - INFO - SSH connection established
2025-07-08 19:01:41,002 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:01:41,141 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:01:41,375 - INFO - Uploading simple_test.py to \home\user\dataset\test_run\simple_test.py
2025-07-08 19:01:41,543 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:01:41,652 - INFO - Uploading main.py to \home\user\dataset\test_run\main.py
2025-07-08 19:01:41,832 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:01:41,972 - INFO - Uploading config.json to \home\user\dataset\test_run\config.json
2025-07-08 19:01:42,152 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:01:42,259 - INFO - Uploading topology.py to \home\user\dataset\test_run\topology.py
2025-07-08 19:01:42,387 - INFO - Executing: mkdir -p \home\user\dataset\test_run\controller
2025-07-08 19:01:42,523 - INFO - Uploading controller\ryu_controller_app.py to \home\user\dataset\test_run\controller\ryu_controller_app.py
2025-07-08 19:01:42,696 - INFO - Executing: mkdir -p \home\user\dataset\test_run\attacks
2025-07-08 19:01:42,804 - INFO - Uploading attacks\gen_syn_flood.py to \home\user\dataset\test_run\attacks\gen_syn_flood.py
2025-07-08 19:01:42,919 - INFO - Executing: mkdir -p \home\user\dataset\test_run\attacks
2025-07-08 19:01:43,045 - INFO - Uploading attacks\gen_udp_flood.py to \home\user\dataset\test_run\attacks\gen_udp_flood.py
2025-07-08 19:01:43,166 - INFO - Executing: mkdir -p \home\user\dataset\test_run\attacks
2025-07-08 19:01:43,271 - INFO - Uploading attacks\gen_advanced_adversarial_ddos_attacks.py to \home\user\dataset\test_run\attacks\gen_advanced_adversarial_ddos_attacks.py
2025-07-08 19:01:43,457 - INFO - Running environment check...
2025-07-08 19:01:43,457 - INFO - Executing: cd \home\user\dataset\test_run && python3 simple_test.py
2025-07-08 19:01:43,574 - INFO - Output: python3: can't open file 'simple_test.py': [Errno 2] No such file or directory
2025-07-08 19:01:43,575 - ERROR - Environment check failed
2025-07-08 19:02:42,278 - INFO - Starting remote test execution...
2025-07-08 19:02:42,279 - INFO - Connecting to user@jtmksrv:656
2025-07-08 19:02:45,043 - INFO - Connected (version 2.0, client OpenSSH_7.6p1)
2025-07-08 19:02:45,206 - INFO - Authentication (password) successful!
2025-07-08 19:02:45,407 - INFO - [chan 0] Opened sftp connection (server version 3)
2025-07-08 19:02:45,408 - INFO - SSH connection established
2025-07-08 19:02:45,409 - INFO - Executing: mkdir -p \home\user\dataset\test_run
2025-07-08 19:02:45,542 - INFO - Executing: mkdir -p /home/user/dataset/test_run/controller
2025-07-08 19:02:45,801 - INFO - Executing: mkdir -p /home/user/dataset/test_run/attacks
2025-07-08 19:02:45,998 - INFO - Uploading simple_test.py to /home/user/dataset/test_run/simple_test.py
2025-07-08 19:02:46,230 - INFO - Uploaded simple_test.py to /home/user/dataset/test_run/simple_test.py
2025-07-08 19:02:46,232 - INFO - Uploading main.py to /home/user/dataset/test_run/main.py
2025-07-08 19:02:46,359 - INFO - Uploaded main.py to /home/user/dataset/test_run/main.py
2025-07-08 19:02:46,361 - INFO - Uploading config.json to /home/user/dataset/test_run/config.json
2025-07-08 19:02:46,481 - INFO - Uploaded config.json to /home/user/dataset/test_run/config.json
2025-07-08 19:02:46,482 - INFO - Uploading topology.py to /home/user/dataset/test_run/topology.py
2025-07-08 19:02:46,550 - INFO - Uploaded topology.py to /home/user/dataset/test_run/topology.py
2025-07-08 19:02:46,550 - INFO - Uploading controller\ryu_controller_app.py to /home/user/dataset/test_run/controller/ryu_controller_app.py
2025-07-08 19:02:46,688 - INFO - Uploaded controller\ryu_controller_app.py to /home/user/dataset/test_run/controller/ryu_controller_app.py
2025-07-08 19:02:46,688 - INFO - Uploading attacks\gen_syn_flood.py to /home/user/dataset/test_run/attacks/gen_syn_flood.py
2025-07-08 19:02:46,752 - INFO - Uploaded attacks\gen_syn_flood.py to /home/user/dataset/test_run/attacks/gen_syn_flood.py
2025-07-08 19:02:46,753 - INFO - Uploading attacks\gen_udp_flood.py to /home/user/dataset/test_run/attacks/gen_udp_flood.py
2025-07-08 19:02:46,822 - INFO - Uploaded attacks\gen_udp_flood.py to /home/user/dataset/test_run/attacks/gen_udp_flood.py
2025-07-08 19:02:46,823 - INFO - Uploading attacks\gen_advanced_adversarial_ddos_attacks.py to /home/user/dataset/test_run/attacks/gen_advanced_adversarial_ddos_attacks.py
2025-07-08 19:02:46,934 - INFO - Uploaded attacks\gen_advanced_adversarial_ddos_attacks.py to /home/user/dataset/test_run/attacks/gen_advanced_adversarial_ddos_attacks.py
2025-07-08 19:02:46,935 - INFO - Running environment check...
2025-07-08 19:02:46,935 - INFO - Executing: cd /home/user/dataset/test_run && python3 simple_test.py
2025-07-08 19:02:47,062 - INFO - Output: 2025-07-08 19:02:47,522 - INFO - Starting simple test...
2025-07-08 19:02:47,522 - INFO - Checking environment...
2025-07-08 19:02:47,522 - INFO - Environment check passed
2025-07-08 19:02:47,522 - INFO - Created test configuration file: test_config.json
2025-07-08 19:02:47,522 - INFO - Test setup complete. You can now run the test with:
2025-07-08 19:02:47,522 - INFO - sudo python3 main.py test_config.json
2025-07-08 19:02:47,063 - INFO - Installing dependencies...
2025-07-08 19:02:47,064 - INFO - Executing: echo 1 | sudo -S pip3 install mininet ryu scapy pandas
2025-07-08 19:02:54,111 - INFO - Output: [sudo] password for user: /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.utils import int_from_bytes
[33mWARNING: The directory '/home/user/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.[0m
Requirement already satisfied: mininet in /usr/local/lib/python3.6/dist-packages/mininet-2.3.1b4-py3.6.egg (2.3.1b4)
Requirement already satisfied: ryu in /usr/local/lib/python3.6/dist-packages (4.34)
Requirement already satisfied: scapy in /usr/local/lib/python3.6/dist-packages (2.5.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.1.5)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from mininet) (39.0.1)
Requirement already satisfied: msgpack>=0.3.0 in ./.local/lib/python3.6/site-packages (from ryu) (1.0.5)
Requirement already satisfied: routes in ./.local/lib/python3.6/site-packages (from ryu) (2.5.1)
Requirement already satisfied: oslo.config>=2.5.0 in ./.local/lib/python3.6/site-packages (from ryu) (8.8.1)
Requirement already satisfied: webob>=1.2 in ./.local/lib/python3.6/site-packages (from ryu) (1.8.9)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from ryu) (1.11.0)
Requirement already satisfied: eventlet!=0.18.3,!=0.20.1,!=0.21.0,!=0.23.0,>=0.18.2 in /usr/local/lib/python3.6/dist-packages (from ryu) (0.30.2)
Requirement already satisfied: tinyrpc in ./.local/lib/python3.6/site-packages (from ryu) (1.1.7)
Requirement already satisfied: ovs>=2.6.0 in ./.local/lib/python3.6/site-packages (from ryu) (3.5.0)
Requirement already satisfied: netaddr in ./.local/lib/python3.6/site-packages (from ryu) (0.10.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas) (2018.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: dnspython<2.0.0,>=1.15.0 in /usr/local/lib/python3.6/dist-packages (from eventlet!=0.18.3,!=0.20.1,!=0.21.0,!=0.23.0,>=0.18.2->ryu) (1.16.0)
Requirement already satisfied: greenlet>=0.3 in ./.local/lib/python3.6/site-packages (from eventlet!=0.18.3,!=0.20.1,!=0.21.0,!=0.23.0,>=0.18.2->ryu) (2.0.2)
Requirement already satisfied: rfc3986>=1.2.0 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (1.5.0)
Requirement already satisfied: oslo.i18n>=3.15.3 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (5.1.0)
Requirement already satisfied: PyYAML>=5.1 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (6.0.1)
Requirement already satisfied: debtcollector>=1.2.0 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (2.5.0)
Requirement already satisfied: importlib-metadata>=1.7.0 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (4.8.3)
Requirement already satisfied: requests>=2.18.0 in /usr/lib/python3/dist-packages (from oslo.config>=2.5.0->ryu) (2.18.4)
Requirement already satisfied: stevedore>=1.20.0 in ./.local/lib/python3.6/site-packages (from oslo.config>=2.5.0->ryu) (3.5.2)
Requirement already satisfied: importlib-resources in ./.local/lib/python3.6/site-packages (from netaddr->ryu) (5.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.6/dist-packages (from ovs>=2.6.0->ryu) (2.4.0)
Requirement already satisfied: repoze.lru>=0.3 in ./.local/lib/python3.6/site-packages (from routes->ryu) (0.7)
Requirement already satisfied: wrapt>=1.7.0 in ./.local/lib/python3.6/site-packages (from debtcollector>=1.2.0->oslo.config>=2.5.0->ryu) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./.local/lib/python3.6/site-packages (from importlib-metadata>=1.7.0->oslo.config>=2.5.0->ryu) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.6/site-packages (from importlib-metadata>=1.7.0->oslo.config>=2.5.0->ryu) (3.6.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from oslo.i18n>=3.15.3->oslo.config>=2.5.0->ryu) (6.1.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m
2025-07-08 19:02:54,112 - INFO - Executing: cd /home/user/dataset/test_run && ls -la
2025-07-08 19:02:54,280 - INFO - Output: total 48
drwxrwxr-x 4 user user  4096 Jul  8 19:02 .
drwxrwxr-x 3 user user  4096 Jul  8 19:02 ..
drwxrwxr-x 2 user user  4096 Jul  8 19:02 attacks
-rw-rw-r-- 1 user user  2857 Jul  8 19:02 config.json
drwxrwxr-x 2 user user  4096 Jul  8 19:02 controller
-rw-rw-r-- 1 user user 10755 Jul  8 19:02 main.py
-rw-rw-r-- 1 user user   411 Jul  8 19:02 simple_test.log
-rw-rw-r-- 1 user user  3524 Jul  8 19:02 simple_test.py
-rw-rw-r-- 1 user user  1024 Jul  8 19:02 test_config.json
-rw-rw-r-- 1 user user   391 Jul  8 19:02 topology.py
2025-07-08 19:02:54,280 - INFO - Starting test...
2025-07-08 19:02:54,280 - INFO - Executing: cd /home/user/dataset/test_run && sudo python3 main.py test_config.json
